GaurikSystem/Controllers/PaymentController.cs
using GaurikSystem.Models;
using GaurikSystem.Provider.AuthorizeNet;
using System;
using System.Web.Mvc;

namespace GaurikSystem.Controllers
{
    [Authorize]
    public class PaymentController : Controller
    {
        private readonly AuthorizeNetPaymentProcessor _authorizeNetPaymentProcessor;
        public PaymentController()
        {
            _authorizeNetPaymentProcessor = new AuthorizeNetPaymentProcessor();

        }
        // GET: Payment
        public ActionResult Index()
        {
            return View();
        }
        //[Authorize]
       [Route("pay")]
        public ActionResult Pay()
        {
            
            return View(new BillPaymentCardDetailModel());
        }
       // [Authorize]
        [HttpPost]
        [Route("pay")]
        public ActionResult Pay(BillPaymentCardDetailModel model)
        {
            if (model.OrderGuid == null)
                model.OrderGuid = Guid.NewGuid().ToString();
            if (ModelState.IsValid)
            {
                var payment = _authorizeNetPaymentProcessor.ProcessPayment(model);
                if (payment.Success)
                {
                    //To-do Send Email
                    return View("PaymentSuccess");
                }
                else
                {
                    foreach(var error in payment.Errors)
                    {
                        ModelState.AddModelError("", error);
                    }
                }

            }
            
            return View(model);
        }
    }
}

GaurikSystem/Views/Payment/Pay.cshtml
@model GaurikSystem.Models.BillPaymentCardDetailModel

@{
    ViewBag.Title = "Pay";

}
<section class="breadcrumb section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="page-title text-center text-uppercase">Payment Details</h2>
            </div>
        </div>
    </div>
</section><!-- Breadcrumb Area section End Here-->

<div class="inner-main-content">
    <div class="container">

        <div class="row section justify-content-center">
            <div class="col-lg-6 col-md-6 col-sm-12">
                <div id="pay-invoice" class="card">
                    <div class="card-body">
                        <div class="card-title">
                            <h3 class="text-center">Pay Invoice</h3>
                        </div>
                        <hr>
                        @using (Html.BeginForm("Pay", "Payment", FormMethod.Post))
                        {
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="form-group text-center">
                                <ul class="list-inline">
                                    <li class="list-inline-item"><i class="text-muted fa fa-cc-visa fa-2x"></i></li>
                                    <li class="list-inline-item"><i class="fa fa-cc-mastercard fa-2x"></i></li>
                                    <li class="list-inline-item"><i class="fa fa-cc-amex fa-2x"></i></li>
                                    <li class="list-inline-item"><i class="fa fa-cc-discover fa-2x"></i></li>
                                </ul>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.TotalAmount, htmlAttributes: new { @class = "control-label mb-1" })

                                @Html.EditorFor(model => model.TotalAmount, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.TotalAmount, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group has-success">
                                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label mb-1" })
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control cc-name valid" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "help-block field-validation-valid" })
                            </div>
                            <div class="form-group">
                                <label for="cc-number" class="control-label mb-1">Card number</label>

                                <input id="CreditCardNumber" name="CreditCardNumber" type="tel" class="form-control cc-number identified visa" value="@Model.CreditCardNumber" data-val="true" data-val-required="Please enter the card number" data-val-cc-number="Please enter a valid card number" autocomplete="cc-number">
                                <span class="help-block" data-valmsg-for="cc-number" data-valmsg-replace="true"></span>
                                @Html.ValidationMessageFor(model => model.CreditCardNumber, "", new { @class = "text-danger" })
                            </div>
                            <div class="row">
                                <div class="col-6">
                                    <div class="form-group">
                                        <label for="cc-exp" class="control-label mb-1">Expiration</label>
                                        @Html.DropDownListFor(model => model.CreditCardExpireYear, Enumerable.Range(DateTime.Now.Year, 10).Select(x => new SelectListItem { Text = x.ToString(), Value = x.ToString().Substring(2, 2) }), "Expiry Year", new { @class = "form-control cc-exp" })
                                        @Html.ValidationMessageFor(model => model.CreditCardExpireYear, "", new { @class = "text-danger" })
                                        @Html.DropDownListFor(model => model.CreditCardExpireMonth, Enumerable.Range(1, 12).Select(x => new SelectListItem { Text = x.ToString(), Value = x.ToString() }), "Expiry Month", new { @class = "form-control cc-exp" })
                                        <span class="help-block" data-valmsg-for="cc-exp" data-valmsg-replace="true"></span>
                                        @Html.ValidationMessageFor(model => model.CreditCardExpireMonth, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-6">
                                    <label for="x_card_code" class="control-label mb-1">Security code</label>
                                    <div class="input-group">


                                        @Html.EditorFor(model => model.CreditCardCvv2, new { htmlAttributes = new { @class = "form-control cc-cvc" } })
                                        @*<input id="x_card_code" name="x_card_code" type="tel" class="form-control cc-cvc" value="" data-val="true" data-val-required="Please enter the security code" data-val-cc-cvc="Please enter a valid security code" autocomplete="off">*@
                                        <div class="input-group-addon">
                                            <span class="fa fa-question-circle fa-lg" data-toggle="popover" data-container="body" data-html="true" data-title="Security Code"
                                                  data-content="<div class='text-center one-card'>The 3 digit code on back of the card..<div class='visa-mc-cvc-preview'></div></div>"
                                                  data-trigger="hover"></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @*<div class="form-group">
                                    <label for="x_zip" class="control-label mb-1">Postal code</label>
                                    <input id="x_zip" name="x_zip" type="text" class="form-control" value="" data-val="true" data-val-required="Please enter the ZIP/Postal code" autocomplete="postal-code">
                                    <span class="help-block" data-valmsg-for="x_zip" data-valmsg-replace="true"></span>
                                </div>*@

                            @Html.Hidden("CountryTwoLetterIsoCode", "US")

                            <div class="form-group">
                                @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label mb-1" })
                                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.StateProvinceAbbreviation, htmlAttributes: new { @class = "control-label mb-1" })

                                @Html.DropDownListFor(x => x.StateProvinceAbbreviation, GaurikSystem.Helper.Utilities.GetStatesList(), new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Address1, htmlAttributes: new { @class = "control-label mb-1" })

                                @Html.EditorFor(model => model.Address1, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Address1, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.ZipPostalCode, htmlAttributes: new { @class = "control-label mb-1" })
                                @Html.EditorFor(model => model.ZipPostalCode, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ZipPostalCode, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Company, htmlAttributes: new { @class = "control-label mb-1" })

                                @Html.EditorFor(model => model.Company, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Company, "", new { @class = "text-danger" })

                            </div>
                            <div class="form-group has-success">
                                <label for="cc-name" class="control-label mb-1">Name on card</label>
                                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", @placeholder = "First Name" } })
                                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Last Name" } })
                                <span class="help-block field-validation-valid" data-valmsg-for="cc-name" data-valmsg-replace="true"></span>
                            </div>
                            <div>
                                <button id="payment-button" type="submit" class="btn btn-info btn-block">
                                    <!-- <i class="fa fa-lock fa-lg"></i>&nbsp; -->
                                    <span id="payment-button-amount" class="text-uppercase">Submit</span>
                                </button>
                            </div>




                        }



                    </div>
                </div>
            </div>
        </div>


    </div>

</div><!-- inner-main-content -->

GaurikSystem/Views/Payment/PaymentSuccess.cshtml
@model GaurikSystem.Models.BillPaymentCardDetailModel

@{
    ViewBag.Title = "Payment Success";
}
<section class="breadcrumb section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="page-title text-center text-uppercase">Payment Success</h2>
            </div>
        </div>
    </div>
</section><!-- Breadcrumb Area section End Here-->